import { useState, useEffect, useRef, useMemo } from 'react';
import { flushSync } from 'react-dom';
import './settings.css';
import { getVersion } from '@tauri-apps/api/app';
import { openUrl } from '@tauri-apps/plugin-opener';
import { useSettingsStore } from '../../store/settingsStore';
import { useProviderStore } from '../../store/providerStore';
import { useAggregationStore } from '../../store/aggregationStore';
import { useT, t } from '../../i18n';
import {
  Button,
  Input,
  Switch,
  toast,
  ConfirmDialog,
} from '../../components/ui';
import { SegmentedControl, type SegmentedOption } from '../../components/interior/segmented-control';
import { desktopApi, onUpdateAvailable, type UpdateMetadata } from '../../lib/desktopApi';
import { LoadingButton, useAsyncAction } from '../../components/interior/loading-button';
import { useCopyToClipboard } from '../../components/interior/copy-button';
import { useIconMorph, MorphGlyph } from '../../components/interior/icon-morph';
import { TagInput } from '../../components/interior/tag-input';
import { ProgressBar } from '../../components/interior/progress-bar';
import { Modal } from '../../components/interior/modal';
import { TooltipGroup, Tooltip } from '../../components/interior/tooltip-group';
import { Tabs } from '../../components/interior/tabs';
import { Settings as SettingsIcon, Shield, Sliders, Info } from 'lucide-react';
import { isValidHex, normalizeHex } from '../../lib/colorUtils';
import type { SettingsCategory } from '../../types/settings';
import { scheduleLatestProgressFrame } from '../../lib/updateProgress';
import {
  Sun,
  Moon,
  Monitor,
  RefreshCw,
  Download,
  HelpCircle,
  Rss,
  Globe,
  MessageSquare,
} from 'lucide-react';

// Inline GitHub mark — lucide-react deliberately omits brand icons
// (trademark policy), so we ship a simple 20px monochrome mark that
// inherits currentColor, matching the surrounding icon style.
const GithubMark: React.FC<{ size?: number }> = ({ size = 20 }) => (
  <svg
    width={size}
    height={size}
    viewBox="0 0 24 24"
    fill="currentColor"
    xmlns="http://www.w3.org/2000/svg"
    aria-hidden="true"
  >
    <path d="M12 .5C5.65.5.5 5.65.5 12c0 5.08 3.29 9.39 7.86 10.91.58.1.79-.25.79-.56 0-.28-.01-1.02-.02-2-3.2.69-3.88-1.54-3.88-1.54-.52-1.33-1.28-1.68-1.28-1.68-1.05-.72.08-.7.08-.7 1.16.08 1.77 1.19 1.77 1.19 1.03 1.76 2.7 1.25 3.36.96.1-.75.4-1.25.73-1.54-2.55-.29-5.24-1.28-5.24-5.68 0-1.25.45-2.28 1.18-3.09-.12-.29-.51-1.46.11-3.05 0 0 .97-.31 3.17 1.18.92-.26 1.9-.38 2.88-.39.98.01 1.96.13 2.88.39 2.2-1.49 3.17-1.18 3.17-1.18.62 1.59.23 2.76.11 3.05.73.81 1.18 1.84 1.18 3.09 0 4.41-2.69 5.38-5.25 5.67.41.35.78 1.05.78 2.12 0 1.53-.01 2.77-.01 3.14 0 .31.21.67.8.56C20.22 21.38 23.5 17.08 23.5 12 23.5 5.65 18.35.5 12 .5z" />
  </svg>
);

function generateAuthToken(): string {
  // Keep manually refreshed tokens in the same canonical UUID v4 format as
  // tokens generated by the Rust backend during initialization.
  const bytes = new Uint8Array(16);
  crypto.getRandomValues(bytes);

  // RFC 4122 version 4 UUID: random value with the version and variant bits
  // fixed to the UUID v4 layout used by uuid::Uuid::new_v4().
  bytes[6] = (bytes[6] & 0x0f) | 0x40;
  bytes[8] = (bytes[8] & 0x3f) | 0x80;

  const hex = Array.from(bytes, (b) => b.toString(16).padStart(2, '0')).join('');
  return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-${hex.slice(12, 16)}-${hex.slice(16, 20)}-${hex.slice(20)}`;
}

const languageOptions: SegmentedOption[] = [
  { value: 'zh-CN', label: '简体中文' },
  { value: 'en', label: 'English' },
];

const concurrencyOptions: SegmentedOption[] = [
  { value: '1', label: '1' },
  { value: '5', label: '5' },
  { value: '10', label: '10' },
  { value: '20', label: '20' },
  { value: '50', label: '50' },
];

const pageSizeOptions: SegmentedOption[] = [
  { value: '10', label: '10' },
  { value: '20', label: '20' },
  { value: '50', label: '50' },
  { value: '100', label: '100' },
];

const proxyProtocolOptions: SegmentedOption[] = [
  { value: 'http', label: 'HTTP' },
  { value: 'socks5', label: 'SOCKS5' },
];

const COLOR_PRESETS = ['#00B95C', '#2F74FF', '#7C3AED', '#E8463A', '#F2A90C', '#E91E8C', '#00B6F5', '#171717'];

const errorMessage = (e: unknown, fallback: string) => (e instanceof Error ? e.message : e ? String(e) : fallback);

interface SettingsGroupProps {
  title?: string;
  isNew?: boolean;
  /** 标题行右侧附加内容（如「关于」组的 GitHub 入口），随 title 复用同一渲染。 */
  extra?: React.ReactNode;
  children: React.ReactNode;
  style?: React.CSSProperties;
}

const SettingsGroup: React.FC<SettingsGroupProps> = ({ title, isNew, extra, children, style }) => (
  <section
    style={{
      borderBottom: '1px solid var(--border-neutral-l1)',
      ...style,
    }}
  >
    {title && (
      <div
        style={{
          padding: 'var(--spacer-16) var(--spacer-20)',
          fontSize: 'var(--heading-sm-font-size)',
          fontWeight: 'var(--font-weight-strong)',
          lineHeight: 'var(--heading-sm-line-height)',
          color: 'var(--text-default)',
          // 组内分隔靠行间发丝线 + 组级 borderBottom，标题自身不再压线，避免双发丝线。
          display: 'flex',
          alignItems: 'center',
          gap: 'var(--spacer-8)',
        }}
      >
        {title}
        {isNew && (
          <span
            style={{
              // 形态对齐 interior tabs badge：radius-full + overlay 底；颜色走文字态品牌 token。
              fontSize: 'var(--body-xs-font-size)',
              fontWeight: 'var(--font-weight-medium)',
              color: 'var(--text-brand)',
              padding: '1px var(--spacer-6)',
              borderRadius: 'var(--radius-full)',
              background: 'var(--bg-overlay-l2)',
            }}
          >
            New
          </span>
        )}
        {extra && <span style={{ marginLeft: 'auto', display: 'inline-flex' }}>{extra}</span>}
      </div>
    )}
    {children}
  </section>
);

interface SettingsRowProps {
  /** 空/undefined 时不渲染左列（无标签变体，如纯按钮行），不影响右列右侧对齐。 */
  label?: string;
  children: React.ReactNode;
  hint?: string;
  isLast?: boolean;
}

const SettingsRow: React.FC<SettingsRowProps> = ({ label, children, hint, isLast }) => (
  <div
    style={{
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'space-between',
      padding: 'var(--spacer-12) var(--spacer-20)',
      // 48px 保证仅图标/开关控件行也有可点击的舒适高度，与行分隔线节奏一致。
      minHeight: 48,
      boxSizing: 'border-box',
      borderBottom: isLast ? 'none' : '1px solid var(--border-neutral-l1)',
      gap: 'var(--spacer-16)',
    }}
  >
    {label && (
      <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--spacer-2)', flexShrink: 0 }}>
        <span style={{ fontSize: 'var(--body-base-font-size)', lineHeight: 'var(--body-base-line-height)', color: 'var(--text-default)' }}>{label}</span>
        {hint && <span style={{ fontSize: 'var(--body-xs-font-size)', color: 'var(--text-tertiary)' }}>{hint}</span>}
      </div>
    )}
    <div style={{ display: 'flex', alignItems: 'center', gap: 'var(--spacer-8)', marginLeft: 'auto' }}>{children}</div>
  </div>
);

// Link-row for the "关于" links card: icon + label on the left,
// ghost "查看"/"反馈" button on the right. Mirrors the Cherry Studio
// pattern — flat, no border around the whole card, just a bottom
// divider between rows.
interface AboutLinkRowProps {
  icon: React.ReactNode;
  label: string;
  actionLabel: string;
  onClick: () => void;
  isLast?: boolean;
}

const AboutLinkRow: React.FC<AboutLinkRowProps> = ({ icon, label, actionLabel, onClick, isLast }) => (
  <div
    style={{
      display: 'flex',
      alignItems: 'center',
      gap: 'var(--spacer-12)',
      padding: 'var(--spacer-12) var(--spacer-20)',
      minHeight: 48, // 与 SettingsRow 同节奏，保证链接行可点击高度一致。
      boxSizing: 'border-box',
      borderBottom: isLast ? 'none' : '1px solid var(--border-neutral-l1)',
    }}
  >
    <span
      style={{
        display: 'inline-flex',
        alignItems: 'center',
        justifyContent: 'center',
        color: 'var(--text-secondary)',
      }}
    >
      {icon}
    </span>
    <span style={{ fontSize: 'var(--body-base-font-size)', lineHeight: 'var(--body-base-line-height)', color: 'var(--text-default)', flex: 1 }}>{label}</span>
    <Button variant="secondary" size="sm" onClick={onClick}>
      {actionLabel}
    </Button>
  </div>
);

const NumberInput: React.FC<{
  value: number;
  onChange: (v: number) => void;
  min?: number;
  placeholder?: string;
  width?: number;
}> = ({ value, onChange, min, placeholder, width = 80 }) => (
  <Input
    type="number"
    value={value.toString()}
    onChange={(e) => {
      const parsed = parseInt(e.target.value);
      onChange(isNaN(parsed) ? (min ?? 0) : parsed);
    }}
    placeholder={placeholder}
    wrapperStyle={{ width }}
    style={{ textAlign: 'right' }}
  />
);

const TextInput: React.FC<{
  value: string;
  onChange: (v: string) => void;
  placeholder?: string;
  type?: string;
  width?: number;
}> = ({ value, onChange, placeholder, type = 'text', width }) => (
  <Input
    type={type}
    value={value}
    onChange={(e) => onChange(e.target.value)}
    placeholder={placeholder}
    wrapperStyle={width ? { width } : { width: 240 }}
  />
);

export const SettingsForm: React.FC = () => {
  const translate = useT();

  const themeOptions: SegmentedOption[] = [
    { value: 'light', label: translate('settings.theme.light'), icon: <Sun size={15} /> },
    { value: 'dark', label: translate('settings.theme.dark'), icon: <Moon size={15} /> },
    { value: 'system', label: translate('settings.theme.system'), icon: <Monitor size={15} /> },
  ];

  const rateLimitOptions: SegmentedOption[] = [
    { value: '0', label: translate('settings.rateLimit.none') },
    { value: '60', label: translate('settings.rateLimit.perMin', { n: 60 }) },
    { value: '30', label: translate('settings.rateLimit.perMin', { n: 30 }) },
    { value: '10', label: translate('settings.rateLimit.perMin', { n: 10 }) },
  ];

  const retryOptions: SegmentedOption[] = [
    { value: '0', label: translate('settings.retry.none') },
    { value: '1', label: translate('settings.retry.times', { n: 1 }) },
    { value: '3', label: translate('settings.retry.times', { n: 3 }) },
    { value: '5', label: translate('settings.retry.times', { n: 5 }) },
  ];

  const { settings, activeCategory, loaded, loadSettings, setActiveCategory, updateSettings, saveSettingsNow, error, clearError } =
    useSettingsStore();
  // IP 白名单字符串（后端按逗号 split + trim，支持 * 通配符）与 TagInput 数组互转。
  const ipTags = useMemo(
    () => settings.ipWhitelist.split(',').map((s) => s.trim()).filter(Boolean),
    [settings.ipWhitelist],
  );
  const [exporting, setExporting] = useState(false);
  const [openingDir, setOpeningDir] = useState(false);
  const [showToken, setShowToken] = useState(false);
  // 令牌复制改走 interior（fallback + 错误态 + 自动复位，修掉手写版无 fallback 与 setTimeout 泄漏）。
  const tokenCopy = useCopyToClipboard({
    onCopy: () => toast(t('settings.update.tokenCopied'), 'success'),
    onError: () => toast(t('settings.update.copyFailed'), 'error'),
  });
  // 双图标切换统一走路径变形：显隐眼睛、复制→✓（受控，语义不变）。
  const tokenEye = useIconMorph({ preset: 'eye', active: showToken });
  const tokenCopyIcon = useIconMorph({ preset: 'copy-check', active: tokenCopy.copied });
  const [confirmRefreshToken, setConfirmRefreshToken] = useState(false);
  const [confirmResetData, setConfirmResetData] = useState(false);
  const [exportingConfig, setExportingConfig] = useState(false);
  const [pendingImport, setPendingImport] = useState<{ providers: number; aggregations: number; raw: string } | null>(null);
  const importInputRef = useRef<HTMLInputElement>(null);
  // 令牌刷新是纯图标按钮，保留铬、外壳不动，进行态交给 useAsyncAction（防重入 + 自动复位）。
  const refreshTokenAction = useAsyncAction({
    action: async () => {
      try {
        await saveSettingsNow({ authToken: generateAuthToken() });
        toast(t('settings.update.tokenRefreshed'), 'success');
      } catch (e: unknown) {
        toast(errorMessage(e, t('settings.update.saveFailed')), 'error');
      }
    },
  });

  // ── Updater state ──
  // `checking` = in-flight check; `pendingUpdate` = update metadata
  // shown in the confirm dialog; `installing` = download+install in
  // progress; `installProgress` = 0..1 download ratio.
  const [checking, setChecking] = useState(false);
  const [pendingUpdate, setPendingUpdate] = useState<UpdateMetadata | null>(null);
  const [installing, setInstalling] = useState(false);
  const [installProgress, setInstallProgress] = useState(0);
  const [installTotalKnown, setInstallTotalKnown] = useState(false);
  const [appVersion, setAppVersion] = useState('0.0.0');
  const installContentLengthRef = useRef<number | null>(null);
  const installDownloadedRef = useRef<number>(0);
  const installRafRef = useRef<number | null>(null);

  useEffect(
    () => () => {
      if (installRafRef.current !== null) cancelAnimationFrame(installRafRef.current);
    },
    [],
  );

  useEffect(() => {
    if (!loaded) loadSettings();
    getVersion()
      .then(setAppVersion)
      .catch(() => {});
  }, [loaded, loadSettings]);

  useEffect(() => {
    if (error) {
      toast(error, 'error');
      clearError();
    }
  }, [error, clearError]);

  useEffect(() => {
    try {
      desktopApi.initLogDir();
    } catch {
      /* Tauri command may not be available in browser */
    }
  }, []);

  // Startup auto-check listener: when the backend's startup probe
  // finds an update, surface a toast and pre-fill the confirm dialog
  // state so a click on "查看" can open the About page with the
  // metadata ready to install.
  useEffect(() => {
    let unlisten: (() => void) | null = null;
    onUpdateAvailable((meta) => {
      setPendingUpdate(meta);
      toast(t('settings.update.toast', { version: meta.version }), 'info');
    })
      .then((fn) => {
        unlisten = fn;
      })
      .catch(() => {
        /* listener registration can fail when running outside Tauri */
      });
    return () => {
      if (unlisten) unlisten();
    };
  }, []);

  // 检查更新的进行态由 LoadingButton 内部状态机拥有；`checking` 仅保留给“安装更新”按钮的联动禁用。
  const handleCheckUpdates = async () => {
    try {
      const meta = await desktopApi.checkForUpdates();
      if (!meta) {
        toast(t('settings.update.latest'), 'success');
        setPendingUpdate(null);
      } else {
        setPendingUpdate(meta);
      }
    } catch (e) {
      toast(e instanceof Error ? e.message : String(e), 'error');
      throw e;
    }
  };

  const handleInstallUpdate = async () => {
    flushSync(() => {
      setInstalling(true);
      setInstallProgress(0);
      setInstallTotalKnown(false);
    });
    installContentLengthRef.current = null;
    installDownloadedRef.current = 0;
    if (installRafRef.current !== null) {
      cancelAnimationFrame(installRafRef.current);
      installRafRef.current = null;
    }
    await new Promise((resolve) => requestAnimationFrame(() => requestAnimationFrame(resolve)));
    try {
      await desktopApi.downloadAndInstallUpdate((event) => {
        if (event.event === 'started') {
          installContentLengthRef.current = event.data.contentLength ?? null;
          installDownloadedRef.current = 0;
          setInstallTotalKnown(Boolean(event.data.contentLength && event.data.contentLength > 0));
        } else if (event.event === 'progress') {
          installDownloadedRef.current += event.data.chunkLength;
          scheduleLatestProgressFrame(
            installRafRef,
            () => {
              const total = installContentLengthRef.current;
              return total && total > 0 ? Math.min(installDownloadedRef.current / total, 1) : null;
            },
            setInstallProgress,
          );
        } else if (event.event === 'finished') {
          if (installRafRef.current !== null) {
            cancelAnimationFrame(installRafRef.current);
            installRafRef.current = null;
          }
          setInstallTotalKnown(true);
          setInstallProgress(1);
        }
      });
      toast(t('settings.update.installed'), 'success');
      setTimeout(() => {
        desktopApi.exitApp();
      }, 800);
    } catch (e) {
      toast(e instanceof Error ? e.message : String(e), 'error');
      setInstalling(false);
      setInstallProgress(0);
      setInstallTotalKnown(false);
    }
  };

  const handleDismissUpdate = () => {
    if (installing) return;
    setPendingUpdate(null);
    setInstallProgress(0);
    setInstallTotalKnown(false);
  };

  const handleExportLogs = async () => {
    flushSync(() => setExporting(true));
    await new Promise((resolve) => requestAnimationFrame(() => requestAnimationFrame(resolve)));
    try {
      const path = await desktopApi.exportLogs();
      toast(t('settings.update.logExported', { path }), 'success');
    } catch (e: unknown) {
      toast(errorMessage(e, t('settings.update.logExportFailed')), 'error');
    } finally {
      setExporting(false);
    }
  };
  const handleOpenLogDir = async () => {
    flushSync(() => setOpeningDir(true));
    await new Promise((resolve) => requestAnimationFrame(() => requestAnimationFrame(resolve)));
    try {
      await desktopApi.openLogDir();
      toast(t('settings.update.logDirOpened'), 'info');
    } catch (e: unknown) {
      toast(errorMessage(e, t('settings.update.logDirOpenFailed')), 'error');
    } finally {
      setOpeningDir(false);
    }
  };

  const handleRefreshToken = () => {
    if (!loaded || refreshTokenAction.pending) return;
    setConfirmRefreshToken(true);
  };

  const handleExportConfig = async () => {
    setExportingConfig(true);
    try {
      await desktopApi.exportConfig();
      toast(translate('settings.dataManagement.exportSuccess'), 'success');
    } catch (err) {
      toast(errorMessage(err, translate('settings.dataManagement.exportFailed')), 'error');
    } finally {
      setExportingConfig(false);
    }
  };

  const handleConfirmRefreshToken = () => {
    setConfirmRefreshToken(false);
    refreshTokenAction.run();
  };

  const handleCopyToken = () => {
    if (settings.authToken) void tokenCopy.copy(settings.authToken);
  };

  return (
    <>
    <Tabs
      label={t('settings.navLabel')}
      items={[
        { value: 'general', icon: <SettingsIcon size={16} />, label: t('settings.general') },
        { value: 'security', icon: <Shield size={16} />, label: t('settings.security') },
        { value: 'proxy', icon: <Globe size={16} />, label: t('settings.proxy') },
        { value: 'advanced', icon: <Sliders size={16} />, label: t('settings.advanced') },
        { value: 'about', icon: <Info size={16} />, label: t('settings.about') },
      ]}
      value={activeCategory}
      onValueChange={(v) => setActiveCategory(v as SettingsCategory)}
      renderPanel={() => (
        <div className="mh-settings-panel">
      {/* ═══════════════════════════════════════════════════ 通用设置 */}
      {activeCategory === 'general' && (
        <>
          <SettingsGroup title={translate('settings.appearance')}>
            <SettingsRow label={translate('settings.appearanceLang')}>
              <SegmentedControl
                label={translate('settings.appearanceLang')}
                options={languageOptions}
                value={settings.language}
                onValueChange={(v) => updateSettings({ language: v })}
              />
            </SettingsRow>
            <SettingsRow label={translate('settings.appearanceTheme')}>
              <SegmentedControl
                label={translate('settings.appearanceTheme')}
                options={themeOptions}
                value={settings.theme}
                onValueChange={(v) => updateSettings({ theme: v })}
              />
            </SettingsRow>
            <SettingsRow label={translate('settings.appearanceAccent')}>
              <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                <div style={{ display: 'flex', gap: 6 }}>
                  {COLOR_PRESETS.map((color) => {
                    const isSelected = normalizeHex(settings.accentColor) === normalizeHex(color);
                    return (
                      <button
                        key={color}
                        type="button"
                        className="mh-accent-swatch"
                        onClick={() => updateSettings({ accentColor: normalizeHex(color) })}
                        style={{
                          // 28px 色块：单行内多色并列的最小可点击尺寸，保持不变。
                          width: 28,
                          height: 28,
                          borderRadius: '50%',
                          background: color,
                          border: isSelected ? `2px solid ${color}` : '2px solid transparent',
                          // 固定双环写法：外圈 2px 页面底色 + 再外圈 2px 自身色，形成选中描边；
                          // 未选中时仅 1px 中性描边。两态叠序不可调换，否则环色被盖住。
                          boxShadow: isSelected
                            ? `0 0 0 2px var(--bg-base-default), 0 0 0 4px ${color}`
                            : '0 0 0 1px var(--border-neutral-l2)',
                          cursor: 'pointer',
                          padding: 0,
                        }}
                        aria-label={translate('settings.appearanceAccentAria', { color })}
                      />
                    );
                  })}
                </div>
                <Input
                  type="text"
                  value={settings.accentColor}
                  onChange={(e) => {
                    const v = e.target.value;
                    if (isValidHex(v) || v === '#' || v.length < 7) {
                      updateSettings({ accentColor: v.toUpperCase() });
                    }
                  }}
                  onBlur={(e) => {
                    if (isValidHex(e.target.value)) {
                      updateSettings({ accentColor: normalizeHex(e.target.value) });
                    } else {
                      updateSettings({ accentColor: '#00B95C' });
                    }
                  }}
                  wrapperStyle={{ width: 96 }}
                  style={{
                    fontFamily: 'var(--font-family-mono)',
                    fontSize: 13,
                    textAlign: 'center',
                  }}
                  maxLength={7}
                />
              </div>
            </SettingsRow>
            <SettingsRow label={translate('settings.appearancePageSize')} isLast>
              <SegmentedControl
                label={translate('settings.appearancePageSize')}
                options={pageSizeOptions}
                value={settings.pageSize.toString()}
                onValueChange={(v) => updateSettings({ pageSize: parseInt(v) })}
                size="sm"
              />
            </SettingsRow>
          </SettingsGroup>

          <SettingsGroup title={translate('settings.basic')}>
            <SettingsRow label={translate('settings.basicHost')}>
              <TextInput value={settings.host} onChange={(v) => updateSettings({ host: v })} />
            </SettingsRow>
            <SettingsRow label={translate('settings.proxyPort')}>
              <NumberInput value={settings.port} onChange={(v) => updateSettings({ port: v })} min={1} />
            </SettingsRow>
            <SettingsRow label={translate('settings.basicAutoStart')} hint={translate('settings.basicAutoStartHint')}>
              <Switch checked={settings.autoStart} onChange={(v) => updateSettings({ autoStart: v })} />
            </SettingsRow>
            <SettingsRow label={translate('settings.basicMaxConcurrency')} isLast>
              <SegmentedControl
                label={translate('settings.basicMaxConcurrency')}
                options={concurrencyOptions}
                value={settings.maxConcurrency.toString()}
                onValueChange={(v) => updateSettings({ maxConcurrency: parseInt(v) })}
                size="sm"
              />
            </SettingsRow>
          </SettingsGroup>

          <SettingsGroup title={translate('settings.appStartup')}>
            <SettingsRow label={translate('settings.appStartupLaunch')} hint={translate('settings.appStartupLaunchHint')}>
              <Switch checked={settings.launchAtLogin} onChange={(v) => updateSettings({ launchAtLogin: v })} />
            </SettingsRow>
            <SettingsRow label={translate('settings.appStartupMinimized')} hint={translate('settings.appStartupMinimizedHint')} isLast>
              <Switch checked={settings.startMinimized} onChange={(v) => updateSettings({ startMinimized: v })} />
            </SettingsRow>
          </SettingsGroup>
        </>
      )}

      {/* ═══════════════════════════════════════════════════ 安全与认证 */}
      {activeCategory === 'security' && (
        <>
          <SettingsGroup title={translate('settings.security.title')}>
            <SettingsRow label={translate('settings.security.token')}>
              <div style={{ display: 'flex', alignItems: 'center', gap: 4 }}>
                <Input
                  type={showToken ? 'text' : 'password'}
                  value={settings.authToken}
                  onChange={(e) => updateSettings({ authToken: e.target.value })}
                  placeholder={translate('settings.security.tokenPlaceholder')}
                  wrapperStyle={{
                    width: 280,
                    fontFamily: 'var(--font-family-mono)',
                    fontSize: 13,
                  }}
                  style={{ fontFamily: 'var(--font-family-mono)', fontSize: 13 }}
                />
                <TooltipGroup>
                <Tooltip label={showToken ? translate('settings.security.hideToken') : translate('settings.security.showToken')}>
                <button
                  type="button"
                  className="icon-action-btn"
                  onClick={() => setShowToken((v) => !v)}
                  aria-label={showToken ? translate('settings.security.hideToken') : translate('settings.security.showToken')}
                >
                  <MorphGlyph slots={tokenEye.slots} rotate={tokenEye.rotate} transition={tokenEye.transition} mode={tokenEye.mode} size={18} />
                </button>
                </Tooltip>
                <Tooltip label={translate('settings.security.copyTokenAria')}>
                <button
                  type="button"
                  className="icon-action-btn"
                  onClick={handleCopyToken}
                  disabled={!settings.authToken}
                  aria-label={translate('settings.security.copyTokenAria')}
                >
                  <MorphGlyph slots={tokenCopyIcon.slots} rotate={tokenCopyIcon.rotate} transition={tokenCopyIcon.transition} mode={tokenCopyIcon.mode} size={18} />
                </button>
                </Tooltip>
                <Tooltip label={translate('settings.security.refreshTokenTitle')}>
                <button
                  type="button"
                  className="icon-action-btn"
                  onClick={handleRefreshToken}
                  disabled={!loaded || refreshTokenAction.pending}
                  aria-label={translate('settings.security.refreshTokenAria')}
                >
                  <RefreshCw size={18} className={refreshTokenAction.pending ? 'animate-spin' : undefined} />
                </button>
                </Tooltip>
                </TooltipGroup>
              </div>
            </SettingsRow>
            <SettingsRow label={translate('settings.security.ipWhitelist')}>
              <div style={{ width: '100%' }}>
                <TagInput
                  value={ipTags}
                  onChange={(tags) => updateSettings({ ipWhitelist: tags.join(', ') })}
                  separators={[',', ' ']}
                  placeholder={translate('settings.security.ipPlaceholder')}
                  hint={translate('settings.security.ipHint')}
                />
              </div>
            </SettingsRow>
            <SettingsRow label={translate('settings.security.cors')}>
              <Switch checked={settings.corsEnabled} onChange={(v) => updateSettings({ corsEnabled: v })} />
            </SettingsRow>
            <SettingsRow label={translate('settings.security.rateLimit')} isLast>
              <SegmentedControl
                label={translate('settings.security.rateLimit')}
                options={rateLimitOptions}
                value={settings.rateLimit}
                onValueChange={(v) => updateSettings({ rateLimit: v })}
                size="sm"
              />
            </SettingsRow>
          </SettingsGroup>
        </>
      )}

      {/* ═══════════════════════════════════════════════════ 网络代理 */}
      {activeCategory === 'proxy' && (
        <>
          <SettingsGroup title={translate('settings.proxyConfig')}>
            <SettingsRow label={translate('settings.proxyConfigEnable')}>
              <Switch checked={settings.proxyEnabled} onChange={(v) => updateSettings({ proxyEnabled: v })} />
            </SettingsRow>
            <SettingsRow label={translate('settings.proxyConfigHost')}>
              <TextInput
                value={settings.proxyHost}
                onChange={(v) => updateSettings({ proxyHost: v })}
                placeholder="127.0.0.1"
              />
            </SettingsRow>
            <SettingsRow label={translate('settings.proxyConfigPort')}>
              <NumberInput value={settings.proxyPort} onChange={(v) => updateSettings({ proxyPort: v })} min={1} />
            </SettingsRow>
            <SettingsRow label={translate('settings.proxyConfigProtocol')}>
              <SegmentedControl
                label={translate('settings.proxyConfigProtocol')}
                options={proxyProtocolOptions}
                value={settings.proxyProtocol}
                onValueChange={(v) => updateSettings({ proxyProtocol: v })}
                size="sm"
              />
            </SettingsRow>
            <SettingsRow label={translate('settings.proxyConfigUsername')}>
              <TextInput
                value={settings.proxyUsername}
                onChange={(v) => updateSettings({ proxyUsername: v })}
                placeholder={translate('common.placeholder')}
              />
            </SettingsRow>
            <SettingsRow label={translate('settings.proxyConfigPassword')} isLast>
              <TextInput
                value={settings.proxyPassword}
                onChange={(v) => updateSettings({ proxyPassword: v })}
                placeholder={translate('common.placeholder')}
                type="password"
              />
            </SettingsRow>
          </SettingsGroup>
        </>
      )}

      {/* ═══════════════════════════════════════════════════ 高级选项 */}
      {activeCategory === 'advanced' && (
        <>
          <SettingsGroup title={translate('settings.advanced.title')}>
            <SettingsRow label={translate('settings.advanced.timeout')}>
              <NumberInput value={settings.apiTimeout} onChange={(v) => updateSettings({ apiTimeout: v })} min={1} />
            </SettingsRow>
            <SettingsRow label={translate('settings.advanced.retries')} isLast>
              <SegmentedControl
                label={translate('settings.advanced.retries')}
                options={retryOptions}
                value={settings.maxRetries}
                onValueChange={(v) => updateSettings({ maxRetries: v })}
                size="sm"
              />
            </SettingsRow>
          </SettingsGroup>

          <SettingsGroup title={translate('settings.logging.title')}>
            <SettingsRow label={translate('settings.logging.retention')}>
              <NumberInput
                value={settings.logRetentionDays}
                onChange={(v) => updateSettings({ logRetentionDays: v })}
                min={1}
              />
            </SettingsRow>
            <SettingsRow label={translate('settings.logging.autoClean')}>
              <Switch checked={settings.logAutoClean} onChange={(v) => updateSettings({ logAutoClean: v })} />
            </SettingsRow>
            <SettingsRow label="" isLast>
              <Button disabled={exporting} onClick={handleExportLogs}>
                {exporting ? translate('settings.logging.exporting') : translate('settings.logging.export')}
              </Button>
              <Button disabled={openingDir} variant="secondary" onClick={handleOpenLogDir}>
                {openingDir ? translate('settings.logging.opening') : translate('settings.logging.openDir')}
              </Button>
            </SettingsRow>
          </SettingsGroup>
        </>
      )}

      {/* ═══════════════════════════════════════════════════ 关于 */}
      {activeCategory === 'about' && (
        <>
          {/* ── About / Update card ────────────────────────── */}
          <SettingsGroup
            title={translate('settings.about.title')}
            extra={
              <button
                type="button"
                onClick={() => openUrl('https://github.com/Lhy723/MelodyHub').catch(() => {})}
                title={translate('settings.about.githubTitle')}
                style={{
                  display: 'inline-flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                  width: 32,
                  height: 32,
                  padding: 0,
                  border: 'none',
                  borderRadius: 'var(--radius-8)',
                  background: 'transparent',
                  color: 'var(--text-tertiary)',
                  cursor: 'pointer',
                  transition: 'background var(--transition-fast), color var(--transition-fast)',
                }}
                onMouseEnter={(e) => {
                  e.currentTarget.style.background = 'var(--bg-overlay-l1)';
                  e.currentTarget.style.color = 'var(--text-default)';
                }}
                onMouseLeave={(e) => {
                  e.currentTarget.style.background = 'transparent';
                  e.currentTarget.style.color = 'var(--text-tertiary)';
                }}
              >
                <GithubMark size={20} />
              </button>
            }
          >
            {/* Hero row: logo + name/slogan/version + check-update button.
                上缘发丝线承接组标题（原手写 divider 改为边框），下缘发丝线与自动更新行分隔。 */}
            <div
              style={{
                display: 'flex',
                alignItems: 'center',
                gap: 'var(--spacer-16)',
                padding: 'var(--spacer-24) var(--spacer-20)',
                borderTop: '1px solid var(--border-neutral-l1)',
                borderBottom: '1px solid var(--border-neutral-l1)',
              }}
            >
              <img
                src="/brand/app-icon-1024.png"
                alt="Melody Hub"
                width={72}
                height={72}
                style={{
                  width: 72,
                  height: 72,
                  borderRadius: 'var(--radius-16)',
                  flexShrink: 0,
                  userSelect: 'none',
                }}
                draggable={false}
              />
              <div style={{ flex: 1, minWidth: 0 }}>
                <div
                  style={{
                    fontSize: 'var(--heading-md-font-size)',
                    fontWeight: 'var(--font-weight-strong)',
                    lineHeight: 'var(--heading-md-line-height)',
                    color: 'var(--text-default)',
                  }}
                >
                  Melody Hub
                </div>
                <div
                  style={{
                    fontSize: 'var(--body-base-font-size)',
                    color: 'var(--text-tertiary)',
                    marginTop: 2,
                  }}
                >
                  {translate('settings.about.slogan')}
                </div>
                <div style={{ marginTop: 8, display: 'inline-flex' }}>
                  <span
                    style={{
                      // 版本徽章中性化对齐 interior tabs badge 形态：radius-full + overlay 底 + 发丝边。
                      fontSize: 'var(--body-sm-font-size)',
                      fontWeight: 'var(--font-weight-medium)',
                      color: 'var(--text-secondary)',
                      padding: '2px 10px',
                      border: '1px solid var(--border-neutral-l1)',
                      borderRadius: 'var(--radius-full)',
                      background: 'var(--bg-overlay-l1)',
                      fontVariantNumeric: 'tabular-nums',
                    }}
                  >
                    v{pendingUpdate?.currentVersion ?? appVersion}
                  </span>
                </div>
              </div>
              <LoadingButton
                onAction={async () => {
                  setChecking(true);
                  try {
                    await handleCheckUpdates();
                  } finally {
                    setChecking(false);
                  }
                }}
                pendingLabel={translate('settings.about.checking')}
                successLabel={translate('settings.about.checked')}
                errorLabel={translate('settings.about.checkFailed')}
                disabled={installing}
              >
                {translate('settings.about.checkUpdate')}
              </LoadingButton>
            </div>

            {/* Auto-update row（与 hero 的分隔线由 hero borderBottom 承担） */}
            <SettingsRow label={translate('settings.about.autoUpdate')} isLast>
              <Switch
                checked={settings.checkUpdatesOnStart}
                onChange={(v) => updateSettings({ checkUpdatesOnStart: v })}
              />
            </SettingsRow>
          </SettingsGroup>

          {/* ── Links card ─────────────────────────────────── */}
          <SettingsGroup>
            <AboutLinkRow
              icon={<HelpCircle size={20} />}
              label={translate('settings.about.helpDocs')}
              actionLabel={translate('settings.about.view')}
              onClick={() => openUrl('https://github.com/Lhy723/MelodyHub#readme').catch(() => {})}
            />
            <AboutLinkRow
              icon={<Rss size={20} />}
              label={translate('settings.about.changelog')}
              actionLabel={translate('settings.about.view')}
              onClick={() => openUrl('https://github.com/Lhy723/MelodyHub/releases').catch(() => {})}
            />
            <AboutLinkRow
              icon={<Globe size={20} />}
              label={translate('settings.about.website')}
              actionLabel={translate('settings.about.view')}
              onClick={() => openUrl('https://github.com/Lhy723/MelodyHub').catch(() => {})}
            />
            <AboutLinkRow
              icon={<MessageSquare size={20} />}
              label={translate('settings.about.feedback')}
              actionLabel={translate('settings.about.submit')}
              onClick={() => openUrl('https://github.com/Lhy723/MelodyHub/issues').catch(() => {})}
              isLast
            />
          </SettingsGroup>

          {/* ── Data management (kept but de-emphasized) ─── */}
          <SettingsGroup title={translate('settings.dataManagement.title')}>
            <SettingsRow label="" isLast>
              <Button onClick={handleExportConfig} disabled={exportingConfig}>
                {translate('settings.dataManagement.export')}
              </Button>
              <Button variant="secondary" onClick={() => importInputRef.current?.click()}>
                {translate('settings.dataManagement.import')}
              </Button>
              <Button variant="secondary" onClick={() => setConfirmResetData(true)}>
                {translate('settings.dataManagement.reset')}
              </Button>
            </SettingsRow>
          </SettingsGroup>
        </>
      )}
        </div>
      )}
      >
    </Tabs>

      {/* ── Update confirm / install dialog ──
          interior Modal 底座:焦点陷阱/inert/Escape 栈/滚动锁来自 useModal；
          安装中禁用全部关闭入口。 */}
      <Modal
        open={!!pendingUpdate}
        onClose={handleDismissUpdate}
        title={translate('settings.update.title')}
        description={pendingUpdate ? `v${pendingUpdate.currentVersion} → v${pendingUpdate.version}` : undefined}
        showClose={!installing}
        closeOnEscape={!installing}
        closeOnBackdrop={!installing}
        footer={
          <>
            <Button variant="secondary" onClick={handleDismissUpdate} disabled={installing}>
              {translate('settings.update.later')}
            </Button>
            <Button
              variant="brand"
              icon={Download}
              loading={installing}
              onClick={handleInstallUpdate}
              disabled={checking}
            >
              {installing ? translate('settings.update.installing') : translate('settings.update.downloadInstall')}
            </Button>
          </>
        }
      >

              {pendingUpdate?.body && (
                <div
                  style={{
                    marginBottom: 'var(--spacer-20)',
                    padding: 'var(--spacer-14)',
                    background: 'var(--bg-base-secondary)',
                    border: '1px solid var(--border-neutral-l1)',
                    borderRadius: 'var(--radius-8)',
                    // maxHeight 160 ≈ 8 行 changelog 预览，超出内滚，弹窗高度可控。
                    maxHeight: 160,
                    overflowY: 'auto',
                    fontSize: 'var(--body-sm-font-size)',
                    color: 'var(--text-default)',
                    whiteSpace: 'pre-wrap',
                    lineHeight: 'var(--body-base-line-height)',
                  }}
                >
                  {pendingUpdate?.body}
                </div>
              )}

              {installing && (
                <div style={{ marginBottom: 'var(--spacer-16)' }}>
                  <ProgressBar
                    value={installTotalKnown ? installProgress * 100 : null}
                    label={
                      installTotalKnown && installProgress >= 1
                        ? translate('settings.update.installing')
                        : translate('settings.update.downloading')
                    }
                    pendingLabel={translate('settings.update.downloading')}
                    completeLabel={translate('settings.update.installing')}
                  />
                </div>
              )}
            </Modal>

      {/* 导入配置：选择文件 → 校验 → 确认覆盖 → 导入并热更新 */}
      <input
        ref={importInputRef}
        type="file"
        accept=".json,application/json"
        style={{ display: 'none' }}
        onChange={async (e) => {
          const file = e.target.files?.[0];
          e.target.value = '';
          if (!file) return;
          try {
            const raw = await file.text();
            const parsed = JSON.parse(raw) as {
              kind?: string;
              settings?: unknown;
              providers?: unknown[];
              aggregations?: unknown[];
            };
            if (parsed.kind !== 'melody-hub-config' || !parsed.settings || !Array.isArray(parsed.providers) || !Array.isArray(parsed.aggregations)) {
              toast(translate('settings.dataManagement.importInvalid'), 'error');
              return;
            }
            setPendingImport({ providers: parsed.providers.length, aggregations: parsed.aggregations.length, raw });
          } catch {
            toast(translate('settings.dataManagement.importInvalid'), 'error');
          }
        }}
      />
      <ConfirmDialog
        open={pendingImport !== null}
        title={translate('settings.dataManagement.importConfirmTitle')}
        message={translate('settings.dataManagement.importConfirmBody')
          .replace('{providers}', String(pendingImport?.providers ?? 0))
          .replace('{aggregations}', String(pendingImport?.aggregations ?? 0))}
        variant="danger"
        confirmLabel={translate('settings.dataManagement.import')}
        cancelLabel={translate('common.cancel')}
        onConfirm={async () => {
          if (!pendingImport) return;
          const raw = pendingImport.raw;
          setPendingImport(null);
          try {
            await desktopApi.importConfig(raw);
            // 重新拉取三域数据（设置/供应商/聚合）以反映导入结果。
            await Promise.all([
              useSettingsStore.getState().loadSettings(),
              useProviderStore.getState().loadProviders(),
              useAggregationStore.getState().loadAggregations(),
            ]);
            toast(translate('settings.dataManagement.importSuccess'), 'success');
          } catch (err) {
            toast(errorMessage(err, translate('settings.dataManagement.importFailed')), 'error');
          }
        }}
        onCancel={() => setPendingImport(null)}
      />
      <ConfirmDialog
        open={confirmResetData}
        title={translate('settings.dataManagement.reset')}
        message={translate('settings.dataManagement.resetConfirm')}
        variant="danger"
        confirmLabel={translate('common.confirm')}
        cancelLabel={translate('common.cancel')}
        onConfirm={() => {
          setConfirmResetData(false);
          toast(translate('settings.dataManagement.resetToast'), 'info');
        }}
        onCancel={() => setConfirmResetData(false)}
      />
      <ConfirmDialog
        open={confirmRefreshToken}
        title={translate('settings.security.refreshTokenTitle')}
        message={
          settings.authToken
            ? translate('settings.update.tokenRefreshConfirm')
            : translate('settings.update.tokenRegenerateConfirm')
        }
        confirmLabel={translate('common.confirm')}
        cancelLabel={translate('common.cancel')}
        onConfirm={handleConfirmRefreshToken}
        onCancel={() => setConfirmRefreshToken(false)}
      />
    </>
  );
};
